import Link from 'next/link';
import Image from 'next/image';
import { ArrowRight, Check } from 'lucide-react';
const steps=[
 ['01','Customer fills in your website form','A local customer requests a carpet or upholstery quote. Their name, contact details and cleaning request go straight into the Business Manager.','form'],
 ['02','Five minutes later, the first reply goes out','The system prepares and sends a friendly email and text so a good Google Ads or website enquiry does not sit waiting.','message'],
 ['03','They reply with the cleaning list','For example: “Lounge, two bedrooms, hall, stairs and landing — professional deep clean please.” The reply is held against their customer record.','workflow'],
 ['04','The system prepares the quote','It reads the cleaning list, applies your chosen pricing rules and produces a draft quote for you to check.','pricing'],
 ['05','Check and send the professional quote','You can change a room, choose another cleaning method, add extras or a deposit, then send a polished quote to the customer.','quote'],
 ['06','The job is booked into the calendar','Once the customer accepts, the quote becomes a booked job. The appointment, address, access notes and payment position sit together in the diary.','calendar'],
 ['07','Send a beautiful booking confirmation','The customer receives a clear confirmation with their date, arrival window, preparation notes and a simple way to contact you.','booking-email'],
 ['08','Keep them informed before you arrive','A reminder can go out a couple of days before, then a short “we are on our way” text on the day of the clean.','arrival'],
 ['09','Ask for the Google review','After the job, send a friendly thank-you message with the review link while the clean is still fresh in their mind.','review'],
 ['10','Bring customers back automatically','Six- and twelve-month reminders can invite customers back, share an offer and turn past jobs into repeat bookings.','rebook'],
];
function Brand(){return <Link href="/" className="brand brand-light"><Image className="brand-logo" src="/business-manager-badge.png" alt="Carpet Cleaning Business Manager" width={58} height={58}/><span><b>Carpet Cleaning</b><strong>Business Manager</strong></span></Link>}
function FormShot(){return <div className="workflow-form-shot"><div className="wf-form-head"><Image src="/business-manager-badge.png" alt="" width={42} height={42}/><span>The Carpet Cleaning Company</span></div><h3>Tell us what you would like cleaned</h3><p>We will use this to give you the right quote.</p><label>Your name<input value="Lauren Smith" readOnly/></label><label>Mobile number<input value="07 802 556 321" readOnly/></label><label>What would you like cleaned?<textarea value="Lounge, two bedrooms, hall, stairs and landing" readOnly/></label><button>Request my quote</button></div>}
function MessageShot(){return <div className="workflow-message-shot"><div className="phone-top">Messages <span>•••</span></div><div className="message-to">To: Lauren Smith</div><div className="sms-bubble"><b>Thank you for your enquiry, Lauren.</b><br/>We’d love to help with your carpet or upholstery cleaning. Please reply with what you would like cleaned and how many rooms or items there are, and we’ll prepare an accurate quote for you.<small>Delivered now</small></div><div className="phone-note">Automatically sent five minutes after the website enquiry.</div></div>}
function EmailShot({type}:{type:string}){const review=type==='review', arrival=type==='arrival', rebook=type==='rebook'; const title=review?'Thank you for choosing us':arrival?'Your carpet clean is coming up':rebook?'Time for a freshen-up?':'Your booking is confirmed'; const body=review?'Hi Lauren, thank you for having us. If you were pleased with the clean, a quick Google review would mean a great deal to our small business.':arrival?'Hi Lauren, just a reminder that your clean is booked for Tuesday, 24 September, between 9:00am and 10:00am. We’ll send a short message when we are on our way.':rebook?'Hi Lauren, it has been six months since your last clean. If your carpets or upholstery could use a refresh, reply here and we’ll help with a new quote.':'Hi Lauren, your carpet cleaning appointment is confirmed. We look forward to seeing you on Tuesday, 24 September at 9:30am.'; return <div className="email-shot"><div className="email-banner"><Image src="/business-manager-badge.png" alt="" width={52} height={52}/><span>THE CARPET CLEANING COMPANY</span></div><div className="email-content"><p className="email-label">{review?'GOOGLE REVIEW':arrival?'APPOINTMENT REMINDER':rebook?'REBOOKING REMINDER':'BOOKING CONFIRMED'}</p><h3>{title}</h3><p>{body}</p>{review&&<button>Leave a Google review</button>}{!review&&<button>{rebook?'Request a new quote':'View your booking details'}</button>}<small>{review?'Sent after a completed job':arrival?'Sent two days before the visit, with an on-the-way update available on the day':rebook?'Set your own six- or twelve-month timing and offers':'A polished confirmation, sent when the job is booked'}</small></div></div>}
function Screen({kind}:{kind:string}){if(kind==='form')return <FormShot/>;if(kind==='message')return <MessageShot/>;if(['booking-email','arrival','review','rebook'].includes(kind))return <EmailShot type={kind}/>;const src=kind==='workflow'?'/current/workflow.png':kind==='pricing'?'/current/pricing.png':kind==='quote'?'/current/quote-builder.png':'/current/calendar.png';return <figure className="workflow-shot"><Image src={src} alt="Carpet Cleaning Business Manager screen" width={1600} height={900}/></figure>}
export default function HowItWorks(){return <main className="workflow-page"><header className="site-header"><nav><Brand/><div className="links"><Link href="/system">System tour</Link><Link href="/features">What’s included</Link><Link href="/sales-training">Sales training</Link></div><Link className="button gold" href="/#demo">Request a demo <ArrowRight size={16}/></Link></nav></header><section className="workflow-hero"><p className="eyebrow">THE AUTOMATED CUSTOMER JOURNEY</p><h1>From a website enquiry to a booked cleaning job.</h1><p>Designed for carpet cleaners who need to respond quickly, quote accurately and never let a good lead slip away.</p><div><span><Check size={15}/> Automatic response after five minutes</span><span><Check size={15}/> Quote draft from the customer’s reply</span><span><Check size={15}/> One clear next step</span></div></section><section className="workflow-list">{steps.map((step,index)=><article className={index%2?'reverse':''} key={step[0]}><div className="workflow-copy"><span>{step[0]}</span><h2>{step[1]}</h2><p>{step[2]}</p>{index===1&&<p className="fine">The wording is yours to edit. The timing is set in your business settings.</p>}</div><Screen kind={step[3]}/></article>)}</section><section className="workflow-end"><div><p className="eyebrow">THE RESULT</p><h2>A system that wins the work, follows it through and brings customers back.</h2><p>You remain in control. The system does the repetitive work quickly, then gives you the booking, review and rebooking actions to approve.</p></div><Link className="button gold" href="/system">Explore every screen <ArrowRight size={17}/></Link></section></main>}
