import Link from 'next/link';
import Image from 'next/image';
import { ArrowRight, Check } from 'lucide-react';
const steps=[
 ['01','Customer fills in your website form','A local customer requests a carpet or upholstery quote. Their name, contact details and cleaning request go straight into the Business Manager.','form'],
 ['02','Five minutes later, the first reply goes out','The system prepares and sends a friendly email and text so a good Google Ads or website enquiry does not sit waiting.','message'],
 ['03','They reply with the cleaning list','For example: “Lounge, two bedrooms, hall, stairs and landing — professional deep clean please.” The reply is held against their customer record.','workflow'],
 ['04','The system prepares the quote','It reads the cleaning list, applies your chosen pricing rules and produces a draft quote for you to check.','pricing'],
 ['05','Check and send the professional quote','You can change a room, choose another cleaning method, add extras or a deposit, then send a polished quote to the customer.','quote'],
 ['06','Accept, book and follow through','Once accepted, the quote moves into the diary with the customer details, notes and payment position together.','calendar'],
];
function Brand(){return <Link href="/" className="brand brand-light"><Image className="brand-logo" src="/business-manager-badge.png" alt="Carpet Cleaning Business Manager" width={58} height={58}/><span><b>Carpet Cleaning</b><strong>Business Manager</strong></span></Link>}
function FormShot(){return <div className="workflow-form-shot"><div className="wf-form-head"><Image src="/business-manager-badge.png" alt="" width={42} height={42}/><span>The Carpet Cleaning Company</span></div><h3>Tell us what you would like cleaned</h3><p>We will use this to give you the right quote.</p><label>Your name<input value="Lauren Smith" readOnly/></label><label>Mobile number<input value="07 802 556 321" readOnly/></label><label>What would you like cleaned?<textarea value="Lounge, two bedrooms, hall, stairs and landing" readOnly/></label><button>Request my quote</button></div>}
function MessageShot(){return <div className="workflow-message-shot"><div className="phone-top">Messages <span>•••</span></div><div className="message-to">To: Lauren Smith</div><div className="sms-bubble"><b>Thank you for your enquiry, Lauren.</b><br/>We’d love to help with your carpet or upholstery cleaning. Please reply with what you would like cleaned and how many rooms or items there are, and we’ll prepare an accurate quote for you.<small>Delivered now</small></div><div className="phone-note">Automatically sent five minutes after the website enquiry.</div></div>}
function Screen({kind}:{kind:string}){if(kind==='form')return <FormShot/>;if(kind==='message')return <MessageShot/>;const src=kind==='workflow'?'/current/workflow.png':kind==='pricing'?'/current/pricing.png':kind==='quote'?'/current/quote-builder.png':'/current/calendar.png';return <figure className="workflow-shot"><Image src={src} alt="Carpet Cleaning Business Manager screen" width={1600} height={900}/></figure>}
export default function HowItWorks(){return <main className="workflow-page"><header className="site-header"><nav><Brand/><div className="links"><Link href="/system">System tour</Link><Link href="/features">What’s included</Link><Link href="/sales-training">Sales training</Link></div><Link className="button gold" href="/#demo">Request a demo <ArrowRight size={16}/></Link></nav></header><section className="workflow-hero"><p className="eyebrow">THE AUTOMATED CUSTOMER JOURNEY</p><h1>From a website enquiry to a booked cleaning job.</h1><p>Designed for carpet cleaners who need to respond quickly, quote accurately and never let a good lead slip away.</p><div><span><Check size={15}/> Automatic response after five minutes</span><span><Check size={15}/> Quote draft from the customer’s reply</span><span><Check size={15}/> One clear next step</span></div></section><section className="workflow-list">{steps.map((step,index)=><article className={index%2?'reverse':''} key={step[0]}><div className="workflow-copy"><span>{step[0]}</span><h2>{step[1]}</h2><p>{step[2]}</p>{index===1&&<p className="fine">The wording is yours to edit. The timing is set in your business settings.</p>}</div><Screen kind={step[3]}/></article>)}</section><section className="workflow-end"><div><p className="eyebrow">THE RESULT</p><h2>A system that responds, follows up and builds the quote for you.</h2><p>You remain in control. The system does the repetitive work quickly, then gives you a clear quote and next action to approve.</p></div><Link className="button gold" href="/system">Explore every screen <ArrowRight size={17}/></Link></section></main>}
