import Link from 'next/link';
import Image from 'next/image';
import { ArrowRight } from 'lucide-react';
const tour=[
 ['01','The enquiry starts on the website','A cleaner’s website explains their services, shows proof of work and gives the customer one clear way to ask for help. The enquiry then lands directly in the Business Manager.','/current/enquiries.png','New enquiry inbox'],
 ['02','Start every day from one working dashboard','See today’s jobs, quotes, follow-ups, daily route and the single next action that needs attention. It gives the cleaner a proper working start point.','/current/dashboard.png','Today dashboard'],
 ['03','Follow a clear customer workflow','The system guides the cleaner from the first enquiry to cleaning list, pricing, quote, agreement, booking, invoice and follow-through.','/current/workflow.png','Customer workflow'],
 ['04','Price the job in the right way','Choose the cleaning method, package and room pricing you want to use. Use your own first-room prices, additional-room rates, services, upholstery prices and specials.','/current/pricing.png','Price book'],
 ['05','Build a quote without starting from scratch','Select the rooms, rugs, sofas or extras. The calculator applies your method and prices, keeps the quote editable, then carries it into the customer’s job flow.','/current/quote-builder.png','Integrated quote calculator'],
 ['06','Book accepted work into a proper diary','The calendar gives the cleaner a monthly, weekly or daily view. A booking can carry the customer, quote, address, directions and job notes with it.','/current/calendar.png','Working calendar'],
 ['07','Keep every customer conversation in one place','Find a customer, see their history and send a text or email from the same record. Enquiries, responses and follow-ups stay linked to the job.','/current/messages.png','Customer messages'],
 ['08','Keep control of your system and your brand','Business details, logo, price book, follow-up timing, text and email connections, card payments and security are held in one settings area.','/current/settings.png','Business settings']
];
export default function System(){return <main className="tour-page"><header><Link href="/" className="brand"><Image className="brand-logo" src="/manager-logo.png" alt="Carpet Cleaning Manager" width={58} height={58}/><b>Carpet Cleaning<br/>Business Manager</b></Link><nav><Link href="/how-it-works">How it works</Link><Link href="/features">Everything inside</Link><Link href="/sales-training">Sales training</Link></nav><Link className="button gold" href="/#demo">Request a demo</Link></header><section className="tour-hero"><p className="eyebrow">THE COMPLETE SYSTEM TOUR</p><h1>From website enquiry to repeat customer, every step is connected.</h1><p>See exactly what each part does, in the order a carpet cleaner uses it during a normal week.</p></section><div className="tour-steps">{tour.map((step,index)=><section className={'tour-step '+(index%2?'reverse':'')} key={step[0]}><div className="tour-copy"><span>{step[0]} / {step[3]}</span><h2>{step[1]}</h2><p>{step[2]}</p>{index===2&&<Link className="text-link" href="/how-it-works">View the full customer journey <ArrowRight size={16}/></Link>}</div><figure><Image src={step[3]} alt={step[3]} width={1440} height={810}/></figure></section>)}</div><section className="tour-finish"><div><p className="eyebrow">ONE COMPLETE BUSINESS SYSTEM</p><h2>Built for the real way carpet cleaners work.</h2><p>Use only the parts you need, then grow into the rest as your business grows.</p></div><Link className="button gold" href="/#demo">Request a demo <ArrowRight size={17}/></Link></section></main>}
